export const supportedCountries = [
  { label: "Aruba", value: "aw" },
  { label: "Afghanistan", value: "af" },
  { label: "Angola", value: "ao" },
  { label: "Anguilla", value: "ai" },
  { label: "Åland Islands", value: "ax" },
  { label: "Albania", value: "al" },
  { label: "Andorra", value: "ad" },
  { label: "United Arab Emirates", value: "ae" },
  { label: "Argentina", value: "ar" },
  { label: "Armenia", value: "am" },
  { label: "American Samoa", value: "as" },
  { label: "Antarctica", value: "aq" },
  { label: "French Southern Territories", value: "tf" },
  { label: "Antigua and Barbuda", value: "ag" },
  { label: "Australia", value: "au" },
  { label: "Austria", value: "at" },
  { label: "Azerbaijan", value: "az" },
  { label: "Burundi", value: "bi" },
  { label: "Belgium", value: "be" },
  { label: "Benin", value: "bj" },
  { label: "Bonaire, Sint Eustatius and Saba", value: "bq" },
  { label: "Burkina Faso", value: "bf" },
  { label: "Bangladesh", value: "bd" },
  { label: "Bulgaria", value: "bg" },
  { label: "Bahrain", value: "bh" },
  { label: "Bahamas", value: "bs" },
  { label: "Bosnia and Herzegovina", value: "ba" },
  { label: "Saint Barthélemy", value: "bl" },
  { label: "Belarus", value: "by" },
  { label: "Belize", value: "bz" },
  { label: "Bermuda", value: "bm" },
  { label: "Bolivia, Plurinational State of", value: "bo" },
  { label: "Brazil", value: "br" },
  { label: "Barbados", value: "bb" },
  { label: "Brunei Darussalam", value: "bn" },
  { label: "Bhutan", value: "bt" },
  { label: "Bouvet Island", value: "bv" },
  { label: "Botswana", value: "bw" },
  { label: "Central African Republic", value: "cf" },
  { label: "Canada", value: "ca" },
  { label: "Cocos (Keeling) Islands", value: "cc" },
  { label: "Switzerland", value: "ch" },
  { label: "Chile", value: "cl" },
  { label: "China", value: "cn" },
  { label: "Côte d'Ivoire", value: "ci" },
  { label: "Cameroon", value: "cm" },
  { label: "Congo, The Democratic Republic of the", value: "cd" },
  { label: "Congo", value: "cg" },
  { label: "Cook Islands", value: "ck" },
  { label: "Colombia", value: "co" },
  { label: "Comoros", value: "km" },
  { label: "Cabo Verde", value: "cv" },
  { label: "Costa Rica", value: "cr" },
  { label: "Cuba", value: "cu" },
  { label: "Curaçao", value: "cw" },
  { label: "Christmas Island", value: "cx" },
  { label: "Cayman Islands", value: "ky" },
  { label: "Cyprus", value: "cy" },
  { label: "Czechia", value: "cz" },
  { label: "Germany", value: "de" },
  { label: "Djibouti", value: "dj" },
  { label: "Dominica", value: "dm" },
  { label: "Denmark", value: "dk" },
  { label: "Dominican Republic", value: "do" },
  { label: "Algeria", value: "dz" },
  { label: "Ecuador", value: "ec" },
  { label: "Egypt", value: "eg" },
  { label: "Eritrea", value: "er" },
  { label: "Western Sahara", value: "eh" },
  { label: "Spain", value: "es" },
  { label: "Estonia", value: "ee" },
  { label: "Ethiopia", value: "et" },
  { label: "Finland", value: "fi" },
  { label: "Fiji", value: "fj" },
  { label: "Falkland Islands (Malvinas)", value: "fk" },
  { label: "France", value: "fr" },
  { label: "Faroe Islands", value: "fo" },
  { label: "Micronesia, Federated States of", value: "fm" },
  { label: "Gabon", value: "ga" },
  { label: "United Kingdom", value: "gb" },
  { label: "Georgia", value: "ge" },
  { label: "Guernsey", value: "gg" },
  { label: "Ghana", value: "gh" },
  { label: "Gibraltar", value: "gi" },
  { label: "Guinea", value: "gn" },
  { label: "Guadeloupe", value: "gp" },
  { label: "Gambia", value: "gm" },
  { label: "Guinea-Bissau", value: "gw" },
  { label: "Equatorial Guinea", value: "gq" },
  { label: "Greece", value: "gr" },
  { label: "Grenada", value: "gd" },
  { label: "Greenland", value: "gl" },
  { label: "Guatemala", value: "gt" },
  { label: "French Guiana", value: "gf" },
  { label: "Guam", value: "gu" },
  { label: "Guyana", value: "gy" },
  { label: "Hong Kong", value: "hk" },
  { label: "Heard Island and McDonald Islands", value: "hm" },
  { label: "Honduras", value: "hn" },
  { label: "Croatia", value: "hr" },
  { label: "Haiti", value: "ht" },
  { label: "Hungary", value: "hu" },
  { label: "Indonesia", value: "id" },
  { label: "Isle of Man", value: "im" },
  { label: "India", value: "in" },
  { label: "British Indian Ocean Territory", value: "io" },
  { label: "Ireland", value: "ie" },
  { label: "Iran, Islamic Republic of", value: "ir" },
  { label: "Iraq", value: "iq" },
  { label: "Iceland", value: "is" },
  { label: "Israel", value: "il" },
  { label: "Italy", value: "it" },
  { label: "Jamaica", value: "jm" },
  { label: "Jersey", value: "je" },
  { label: "Jordan", value: "jo" },
  { label: "Japan", value: "jp" },
  { label: "Kazakhstan", value: "kz" },
  { label: "Kenya", value: "ke" },
  { label: "Kyrgyzstan", value: "kg" },
  { label: "Cambodia", value: "kh" },
  { label: "Kiribati", value: "ki" },
  { label: "Saint Kitts and Nevis", value: "kn" },
  { label: "Korea, Republic of", value: "kr" },
  { label: "Kuwait", value: "kw" },
  { label: "Lao People's Democratic Republic", value: "la" },
  { label: "Lebanon", value: "lb" },
  { label: "Liberia", value: "lr" },
  { label: "Libya", value: "ly" },
  { label: "Saint Lucia", value: "lc" },
  { label: "Liechtenstein", value: "li" },
  { label: "Sri Lanka", value: "lk" },
  { label: "Lesotho", value: "ls" },
  { label: "Lithuania", value: "lt" },
  { label: "Luxembourg", value: "lu" },
  { label: "Latvia", value: "lv" },
  { label: "Macao", value: "mo" },
  { label: "Saint Martin (French part)", value: "mf" },
  { label: "Morocco", value: "ma" },
  { label: "Monaco", value: "mc" },
  { label: "Moldova, Republic of", value: "md" },
  { label: "Madagascar", value: "mg" },
  { label: "Maldives", value: "mv" },
  { label: "Mexico", value: "mx" },
  { label: "Marshall Islands", value: "mh" },
  { label: "North Macedonia", value: "mk" },
  { label: "Mali", value: "ml" },
  { label: "Malta", value: "mt" },
  { label: "Myanmar", value: "mm" },
  { label: "Montenegro", value: "me" },
  { label: "Mongolia", value: "mn" },
  { label: "Northern Mariana Islands", value: "mp" },
  { label: "Mozambique", value: "mz" },
  { label: "Mauritania", value: "mr" },
  { label: "Montserrat", value: "ms" },
  { label: "Martinique", value: "mq" },
  { label: "Mauritius", value: "mu" },
  { label: "Malawi", value: "mw" },
  { label: "Malaysia", value: "my" },
  { label: "Mayotte", value: "yt" },
  { label: "Namibia", value: "na" },
  { label: "New Caledonia", value: "nc" },
  { label: "Niger", value: "ne" },
  { label: "Norfolk Island", value: "nf" },
  { label: "Nigeria", value: "ng" },
  { label: "Nicaragua", value: "ni" },
  { label: "Niue", value: "nu" },
  { label: "Netherlands", value: "nl" },
  { label: "Norway", value: "no" },
  { label: "Nepal", value: "np" },
  { label: "Nauru", value: "nr" },
  { label: "New Zealand", value: "nz" },
  { label: "Oman", value: "om" },
  { label: "Pakistan", value: "pk" },
  { label: "Panama", value: "pa" },
  { label: "Pitcairn", value: "pn" },
  { label: "Peru", value: "pe" },
  { label: "Philippines", value: "ph" },
  { label: "Palau", value: "pw" },
  { label: "Papua New Guinea", value: "pg" },
  { label: "Poland", value: "pl" },
  { label: "Puerto Rico", value: "pr" },
  { label: "Korea, Democratic People's Republic of", value: "kp" },
  { label: "Portugal", value: "pt" },
  { label: "Paraguay", value: "py" },
  { label: "Palestine, State of", value: "ps" },
  { label: "French Polynesia", value: "pf" },
  { label: "Qatar", value: "qa" },
  { label: "Réunion", value: "re" },
  { label: "Romania", value: "ro" },
  { label: "Russian Federation", value: "ru" },
  { label: "Rwanda", value: "rw" },
  { label: "Saudi Arabia", value: "sa" },
  { label: "Sudan", value: "sd" },
  { label: "Senegal", value: "sn" },
  { label: "Singapore", value: "sg" },
  { label: "South Georgia and the South Sandwich Islands", value: "gs" },
  { label: "Saint Helena, Ascension and Tristan da Cunha", value: "sh" },
  { label: "Svalbard and Jan Mayen", value: "sj" },
  { label: "Solomon Islands", value: "sb" },
  { label: "Sierra Leone", value: "sl" },
  { label: "El Salvador", value: "sv" },
  { label: "San Marino", value: "sm" },
  { label: "Somalia", value: "so" },
  { label: "Saint Pierre and Miquelon", value: "pm" },
  { label: "Serbia", value: "rs" },
  { label: "South Sudan", value: "ss" },
  { label: "Sao Tome and Principe", value: "st" },
  { label: "Suriname", value: "sr" },
  { label: "Slovakia", value: "sk" },
  { label: "Slovenia", value: "si" },
  { label: "Sweden", value: "se" },
  { label: "Eswatini", value: "sz" },
  { label: "Sint Maarten (Dutch part)", value: "sx" },
  { label: "Seychelles", value: "sc" },
  { label: "Syrian Arab Republic", value: "sy" },
  { label: "Turks and Caicos Islands", value: "tc" },
  { label: "Chad", value: "td" },
  { label: "Togo", value: "tg" },
  { label: "Thailand", value: "th" },
  { label: "Tajikistan", value: "tj" },
  { label: "Tokelau", value: "tk" },
  { label: "Turkmenistan", value: "tm" },
  { label: "Timor-Leste", value: "tl" },
  { label: "Tonga", value: "to" },
  { label: "Trinidad and Tobago", value: "tt" },
  { label: "Tunisia", value: "tn" },
  { label: "Turkey", value: "tr" },
  { label: "Tuvalu", value: "tv" },
  { label: "Taiwan, Province of China", value: "tw" },
  { label: "Tanzania, United Republic of", value: "tz" },
  { label: "Uganda", value: "ug" },
  { label: "Ukraine", value: "ua" },
  { label: "United States Minor Outlying Islands", value: "um" },
  { label: "Uruguay", value: "uy" },
  { label: "United States", value: "us" },
  { label: "Uzbekistan", value: "uz" },
  { label: "Holy See (Vatican City State)", value: "va" },
  { label: "Saint Vincent and the Grenadines", value: "vc" },
  { label: "Venezuela, Bolivarian Republic of", value: "ve" },
  { label: "Virgin Islands, British", value: "vg" },
  { label: "Virgin Islands, U.S.", value: "vi" },
  { label: "Viet Nam", value: "vn" },
  { label: "Vanuatu", value: "vu" },
  { label: "Wallis and Futuna", value: "wf" },
  { label: "Samoa", value: "ws" },
  { label: "Yemen", value: "ye" },
  { label: "South Africa", value: "za" },
  { label: "Zambia", value: "zm" },
  { label: "Zimbabwe", value: "zw" },
];
